### ISSUE TITLE
Text is blurry compared to Chrome 77

### ISSUE THREAD

**Issue by ToLive** [wavebox/waveboxapp#1121]
* Wavebox Version: 4.11.4
* Operating System & Version: Windows 10

**Expected & actual behavior**
Text should be crisp

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?

Always in every app

**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**

My gpu is Nvidia G710 with latest possible driver. Text is blurry in every app. In the screenshots Chrome is on the left. One screenshot from my corporate portal and second from regular GMail.
![Ticket20191015_0935_3009](https://user-images.githubusercontent.com/2019736/66795696-968f8400-ef2f-11e9-9573-d0f26d8d0700.png)
![Ticket20191015_0930_3008](https://user-images.githubusercontent.com/2019736/66795697-968f8400-ef2f-11e9-935c-3adad6ed61ca.png)
![Ticket20191015_0927_3007](https://user-images.githubusercontent.com/2019736/66795698-968f8400-ef2f-11e9-95e8-e9521d6bc2d6.png)

**Comment by ToLive** [comment]
Hardware acceleration is ON on both apps

**Comment by Thomas101** [comment]
I'll have a play around with some setups here to see if I can reproduce. Are you using a super hidpi monitor?

It could also

**Comment by ToLive** [comment]
> I'll have a play around with some setups here to see if I can reproduce. Are you using a super hidpi monitor?
No, my monitor is 24' with 1920x1080. No Windows built-in zoom, everything is 100%

> I'm not 100% sure this will make a difference, but if you try zooming in with Ctrl+Plus and Ctrl+- does that make any difference?
No difference, I will add new screenshot with 110%
![Ticket20191015_1716_3020](https://user-images.githubusercontent.com/2019736/66823189-ec841c00-ef6f-11e9-964f-64d93d3c05ee.png)

**Comment by ToLive** [comment]
And screenshot from latest Vivaldi browser based on Chromium 77.
Vivaldi is on the left.
![Ticket20191015_1739_3022](https://user-images.githubusercontent.com/2019736/66824613-d3c93580-ef72-11e9-905d-0c607f1fb352.png)

**Comment by Thomas101** [comment]
Thanks, I'll take a look

**Comment by ToLive** [comment]
Maybe this can help https://github.com/electron/electron/issues/10025

**Comment by Thomas101** [comment]
@ToLive nice find! I've still not been able to reproduce here :-(. As for the fix suggested in 10025, the top-level window already has a background colour applied, but ther webview's don't at the moment. Would you be able to give this a quick try to see if it helps your end?

* Go to `Settings` > `Advanced` and click on the `Main Window Custom CSS` button.
* Paste the following...
```css
webview { background-color: #FFF !important; }
```
* Restart the app and see if that's any better

**Comment by ToLive** [comment]
No, still the same(

**Comment by ToLive** [comment]
Additionally, what I already did with no success:
1. Full reinstall with manual folder cleanup
2. Clean reinstall latest NVIDIA driver.
3. Turn OFF any sort on Antialiasing for Wavebox in NVIDIA control panel.
4. Play with DPI checkboxes in shortcut compatibility tab in properties.

**Comment by corpetty** [comment]
bump, this is an issue for me as well (windows 10, latest drivers).  Slack text looks like sh!t compared to browser version.

**Comment by ToLive** [comment]
Yeah, my eyes are really hurting with this thing and I'm starting to use native apps :( Please, help me with this issue. I can give you any assistance, even connection with Teamviewer.

**Comment by ToLive** [comment]
Maybe this also help: https://github.com/mattermost/desktop/issues/560

As I understand, CSS is not enough to fix this issue, it should be in the code in "new BrowserWindow()"

**Comment by ToLive** [comment]
@Thomas101 issue also present in WB10. I sent info to Susan.
Maybe this issue also can help: https://github.com/microsoft/vscode/issues/84214
And link to Chromium tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1006525

**Comment by ToLive** [comment]
Vscode threads have some workarounds that can be helpful. As I understand issue is not Electron specific.

**Comment by ToLive** [comment]
@Thomas101 any update on this? Blurry text is still here and I really tired to hurt my eyes :(

**Comment by Thomas101** [comment]
Hi, still not been able to reproduce this here and it still remains a mystery as to why Chrome vs Wavebox are different.

One thing that may be worth checking, is there any difference in text rendering in the main Wavebox window, vs a new tabbed window in Wavebox?

**Comment by ToLive** [comment]
Hi!

> One thing that may be worth checking, is there any difference in text rendering in the main Wavebox window, vs a new tabbed window in Wavebox?
They are the same.

It is not about only font. Take a look at the https://mockflow.com/#login

![Ticket20200207_1959_3312](https://user-images.githubusercontent.com/2019736/74031593-9c1b4900-49ba-11ea-99f4-129403c49b18.png)

Look at company logo. Wavebox is in the center, Vivaldi is on the right, Chrome is on the left.
Logo in Wavebox is blurry.

**Comment by ToLive** [comment]
![Ticket20200207_2004_3313](https://user-images.githubusercontent.com/2019736/74031884-5612b500-49bb-11ea-9328-e62032fef17f.png)
And this is magnified logos in same order

**Comment by Thomas101** [comment]
@ToLive is there any difference in text rendering in the main Wavebox window, vs a new tabbed window in Wavebox?

**Comment by ToLive** [comment]
@Thomas101 No, if I tested it correctly. See screenshot:
![Ticket20200207_2241_3315](https://user-images.githubusercontent.com/2019736/74043009-42724900-49d1-11ea-8d2e-5a08ba0a280d.png)

**Comment by Thomas101** [comment]
@ToLive how about in an incognito window? I've just seen you have some extensions installed and wondered if they might have any part to play. They shouldn't be running in an incognito window so should give us some info either way

**Comment by Thomas101** [comment]
I've got a fix for this :)

Found a Geforce 710 with a similar size monitor and I'm seeing the same. Off-the-shelf chrome has GPU rasterization disabled by default on that hardware configuration, where-as Wavebox doesn't so I'll figure out why we're not doing the same!

If you disable GPU rasterization manually then it sharpens everything up. In Wavebox go to `chrome://flags/#enable-gpu-rasterization` and change GPU rasterization to be disabled. Then relaunch the app.

**Comment by ToLive** [comment]
@Thomas101 thank you! That solves problem with blurry images, but not fonts. Please, compare flags section, I think it is best place.
On the screenshot:
Left: chrome://flags in incognito window in Wavebox
Right: chrome://flags in latest chrome

![Ticket20200210_1857_3322](https://user-images.githubusercontent.com/2019736/74148316-daf50d00-4c0d-11ea-8de3-c62e41e34ff8.png)

And a bit closer. Wavebox on the top:
![Ticket20200210_1901_3324](https://user-images.githubusercontent.com/2019736/74148436-17286d80-4c0e-11ea-9f16-13a8b78278f8.png)

**Comment by Thomas101** [comment]
What version nvidia drivers are you using at the moment?

**Comment by ToLive** [comment]
@Thomas101 441.87 from 01/06/2020

**Comment by ToLive** [comment]
Updated right now to 442.19, nothing changed

**Comment by ToLive** [comment]
Also I compares chrome://gpu with Vivaldi and it has disabled chrome://flags/#enable-oop-rasterization , not chrome://flags/#enable-gpu-rasterization . Disabling it in Wavebox seems to have similar good effect for images. But not for fonts :(

**Comment by Thomas101** [comment]
I tried a bunch of the flags to see if anything had any effect but didn't find anything.

I'm wondering if there are some fixes either in Windows or the Nvidia drivers that looks out for `chrome`, `vivaldi`, `chromium` in exec specifically. I'm starting a plain chromium build to see if that exhibits the same behaviour as Chrome & Vivaldi and then I'll try changing the application name to see if that changes the behaviour. It takes about a day to run each build from scratch so I'll try to squeeze it between other tasks

**Comment by ToLive** [comment]
@Thomas101 Great, thanks!

Take a look at one more thing. chrome://gpu has different colors than Vivaldi and Chrome. Maybe it is some sort of CSS applying on top and messes things up?

![Ticket20200212_1117_3327](https://user-images.githubusercontent.com/2019736/74321418-e457b400-4d8a-11ea-93a6-3c01e264b06d.png)

**Comment by ToLive** [comment]
Vivaldi has same colors as Chrome

**Comment by Thomas101** [comment]
We've just shipped 10.0.80 to the beta channel, which has a fix for this. Would be great to know if this is better your end too!

**Comment by ToLive** [comment]
@Thomas101 That is awesome! Now it is fixed! THANK YOU!

May I know what was the cause of this issue?

**Comment by Thomas101** [comment]
@ToLive  Pixie dust :)

From what we could figure out, the issue comes up with certain graphics cards on Windows and it's all down to the way the driver combines the rendered font with the background it's rendering on. There are some additional build flags you can give to Chromium to tell it to use DirectWrite for fonts, which doesn't have this issue

**Comment by ToLive** [comment]
Great!

**Comment by Kytrex5625** [comment]
Hey there, I would like to say that, it now seems the issue is back, and I had reset my pc for this, and it still having this issue, any ways to solve this?
![image](https://user-images.githubusercontent.com/89539469/169665283-98ff5b37-0d15-44f9-930e-eb63b59ea360.png)

**Comment by Thomas101** [comment]
@Kytrex5625 can you give some details about which version of Wavebox you're using and the Operating System you're using? Thanks

**Comment by Thomas101** [comment]
Also, are you using any other Chromium browser (i.e Chrome, Edge, Brave, Vivaldi), which versions of these are you using and is the text blurry on these? Just in case it's a GPU driver issue or something
