### ISSUE TITLE
Long delay opening from notification icon

### ISSUE THREAD

**Issue by bmcclure** [wavebox/waveboxapp#304]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.12

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
ElementaryOS Loki (e.g. Ubuntu 16.04)

Clicking the notification icon once to bring up the context menu takes a very long time for me. If I haven't clicked it in a while, it might take 5-10 seconds to come up the first time, whereas clicking any other notification icon to get a context menu happens nearly instantaneously.

Clicking on it subsequent times makes it come up faster and more consistently, but still slower than other apps (e.g. a few seconds of delay).

I do have several different accounts configured: A work Inbox, a work Gmail, a work Calendar, a home Inbox, a home Gmail, a home Calendar, etc. Is it simply the complexity of the menu items (since all of those accounts show up in the menu with child items) making it so slow to respond?

**Comment by Thomas101** [comment]
Hi, thanks for reporting. If you open the terminal and run `dpkg -s libappindicator1` which version does it report is installed?

**Comment by Thomas101** [comment]
Hi, we’ve just released a workaround for this to the beta channel of Wavebox in version 3.1.15. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel).

It would be great to know if the fix works on your install. If you do have any trouble with it though, you can disable the new behaviour by running wavebox with the `--WBLASDisable` flag. E.g. `./Wavebox --WBLASDisable`.

Thanks!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.16. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by bmcclure** [comment]
Thanks so much for the updates on this! I completely lost track of this issue until today, but am thrilled to hear it's made its way to stable already. I'm updating Wavebox now and will give it a try!

**Comment by bmcclure** [comment]
I still have this issue actually. It seemed a little better at first, but now it seems worse than ever. Often clicking the notification icon freezes it for several seconds and then does nothing. And it used to be where once that happened one time, it returned quickly the next time I clicked it, until later on. But now it's rare that I ever get the context menu working reliably, after trying several times it might pop up, or it might not.

**Comment by bmcclure** [comment]
I actually think that whatever is causing the notification menu to be so unresponsive is also often affecting the rest of my system. Whenever Wavebox is running, I've been noticing lately that some letters I type in other windows are missed, as if the system was momentarily locked up and ignored my input. This used to happen occasionally and I didn't attribute it to Wavebox, but now it happens all the time, and often several words are missed when I type sentences, and it only happens when Wavebox is running.

Just to confirm, this is still on Elementary OS Loki.

**Comment by Thomas101** [comment]
Hi, it would be great to know a little bit more about your setup so I can try to reproduce the issue my end
* Which version of Wavebox are you using at the moment?
* Do you remember which distribution method you used to install (e.g. deb/tar/snap...)
* Are you using 32-bit or 64-bit Elementary OS?

Would you also be able to try the following?
1. Download the latest tar version from the [releases page](https://github.com/wavebox/waveboxapp/releases).
2. Extract this somewhere easy to find, e.g. desktop or downloads
3. Quit your currently running version of Wavebox
4. Open the terminal app in Elementary
5. Move into the directory you extracted Wavebox (.e.g `cd ~/Downloads/Wavebox-linux-x64`)
6. Next run Wavebox with the following `./Wavebox`

Once it launches, open a new terminal window and run steps 5 and 6 again. You should see some log messages starting with `[LAS]` as in the screenshot below....
![untitled](https://user-images.githubusercontent.com/103586/29609269-89d48fc6-87ee-11e7-86f3-0131054a997d.png)

...when you tried this did it launch in a reasonable time? Would you be able to post that screenshot?

**Comment by bmcclure** [comment]
At the moment I am using the current beta channel of Wavebox via the apt repository.

I'm using 64-bit Elementary OS Loki, with the latest updates installed.

I ran the steps provided and everything seemed to happen very quickly. Here's the output:

![screenshot from 2017-09-11 11 46 28](https://user-images.githubusercontent.com/277977/30286404-1ed6e1f8-96e7-11e7-9747-21ea0cdfe231.png)

However, after completing these steps, I quit and relaunched Wavebox and it's been working fine there as well. It seems to usually be the case that it works fine for some time, and then usually at some point throughout the day starts crawling.

I did have 5 email accounts with a lot of email messages in them set up. Recently I pared that down to 2 accounts. It didn't seem to help my issues initially, but I'm wondering if that has had any effect on perhaps making it take longer for the issue to start occurring.

I'll continue seeing if I can find any pattern in when the performance of the context menu, and my overall system, starts getting bad when running Wavebox vs when it works fine. Thanks for your help!

**Comment by Thomas101** [comment]
@bmcclure it might also be worth checking the filesize of `~/.local/share/wavebox/` to see if that's grown

**Comment by bmcclure** [comment]
Ah, I wonder if that could have possibly been the issue before. The directory size is small now (516K), but I haven't been experiencing these performance problems in a couple of days now (somewhat ironically since shortly before I tried to reproduce the issue yesterday).

I wonder if perhaps something cleaned the data in that directory, maybe when I removed my additional accounts from Wavebox? The problem didn't clear up immediately after that, so I didn't think it affected anything, though perhaps it is related.

I'll continue to monitor it and see if the issue comes back soon, or if perhaps things are good now. Thanks again!

**Comment by Thomas101** [comment]
It could be down to the number of accounts. If you've got some you use less frequently you can put them to sleep after a period of inactivity. You'll still get notifications but the UI won't be loaded up all the time. There's some info about it [here](https://blog.wavebox.io/put-wavebox-sleeping-tabs-to-the-test/)
