### ISSUE TITLE
Notifications not working on Windows

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#327]
Hived from https://github.com/wavebox/waveboxapp/issues/307

> Hi, just downloaded and am kicking the tires a bit. Noticed that I'm not seeing any notification at all ( using Inbox ). Tried doing a test notification using default and nothing happens. Maybe I'm missing something obvious? Running 3.1.12 on Windows 10

> @Thomas101, that is how I tested it, under Settings > Notifications and clicking Test Notifications. Nothing happen :. I also tested under the accounts tab as well, still nothing. My Unread Mode is set to "Unread Unbundled Messages". The unread indicator seems to be working fine from what I can tell so far. Let me know if you think this is a real issue and would like me to open one up separately.

---

@nicladas I've hived this off here so we can try to get to the bottom of it. In the notifications section, do you see the `Notification Provider` dropdown and if so what is it set to?

If you open the control panel and search for the `Notifications & actions` section do you see Wavebox listed and what are the settings next to it?

![screen shot 2017-07-25 at 10 52 17](https://user-images.githubusercontent.com/103586/28566546-5d8995a2-7127-11e7-84f6-6a631b099432.png)

**Comment by nicladas** [comment]
Hi @Thomas101 , sorry for such a long delay, I was away from my home PC where I have Wavebox installed. I just checked in Notifications and Actions and Wavebox is not listed as an option!

**Comment by nicladas** [comment]
@Thomas101 does this mean I should try to uninstall and reinstall possibly?

**Comment by Thomas101** [comment]
That might be worth trying.

It would also be good to know if you have the enhanced notification provider is available on your machine and if it's enabled. If you open up settings and look for the notifications section do you see the Notification Provider drop-down? Which one is selected? Does swapping between the two and trying a re-test provide any notifications?


![screen shot 2017-08-14 at 10 49 39](https://user-images.githubusercontent.com/103586/29266890-49929b18-80de-11e7-8ffe-4ceca18612b5.png)

**Comment by ToxMox** [comment]
Notifications aren't working for me either. Tried both providers. In the control panel notifications and actions wavebox isn't in the list at all.

**Comment by Thomas101** [comment]
Would you be able to go to View > Developer Tools or use <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>J</kbd> and then click on the console tab. From there paste/type

```
new Notification("Test")
```

and see if anything comes up.

It would also be great to know which windows version you're using so I can see if it's something to do with that. Could you type `winver` into the cortana search box and run it? It will bring up some information about the exact version of Windows 10 that you're using. (More instructions and alternative methods on using winver [here](https://www.windowscentral.com/how-check-your-windows-10-build))

**Comment by ToxMox** [comment]
Winver: 1703 Build 15063.413
Windows 10 x64 Creators

new Notification("Test") didn't pop anything up
![image](https://user-images.githubusercontent.com/22566356/29412383-78e118be-8326-11e7-9c0b-d1858662f2be.png)

**Comment by Thomas101** [comment]
I've updated one of our test boxes to creators but was still seeing them show up. Did they stop working all of a sudden/after a Windows/Wavebox update?

If you try re-installing Wavebox does that make any difference?

**Comment by ToxMox** [comment]
I don't remember if they were ever working on this PC. They work on my home PC. I downloaded the installer yesterday and reinstalled but that didn't help. I didn't uninstall first though not sure if that makes a difference?

**Comment by nicladas** [comment]
Mine is 
Version 1703 (OS Build 15063.540)
Windows 10 x64 Home

I also don't see any option for developer tools in the app itself and Ctrl+Alt+J doesn't do anything

**Comment by ToxMox** [comment]
Figured out my issue. I had this off:
http://i.imgur.com/EEenjuh.png

Sorry for the confusion from me. Not sure if this is why others have the problem.

**Comment by Thomas101** [comment]
Ah! That might explain it. @nicladas can you check to see what the status of your setting is?

**Comment by nicladas** [comment]
@Thomas101 this enabled for me, but as I mentioned previously, I don't even have Wavebox listed as an option under the Notifications and Actions panel.

**Comment by Thomas101** [comment]
@nicladas  Would you be able to try the `new Notification("test")` from above? I've just checked and the keyboard shortcut should have been <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> rather than <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>J</kbd>. Sorry!

**Comment by nicladas** [comment]
@Thomas101, didn't work for me either:
![image](https://user-images.githubusercontent.com/5066450/30041013-4860b978-91b4-11e7-97b7-9b0e769d841e.png)

**Comment by nmat** [comment]
I can confirm this in the beta branch. If I install stable then the notifications seems to work ok.

**Comment by eatcodeplay** [comment]
Can confirm on latest 3.3.3beta, notification are not working under Windows 10.

**Comment by Thomas101** [comment]
@nmat really weird! The notification code should be the same between the two branches at the moment.

@nmat @eatcodeplay have you both tried...
* Open Wavebox settings, hit `Test Notification`.
* If the `notification provider` dropdown is available, try switching and retrying `Test Notification`.
* If you open the windows Notification settings from the control panel, is Wavebox listed and does it have banners & sounds enabled
* Is the `Get Notifications from apps and other senders` also enabled [see screenshot](http://i.imgur.com/EEenjuh.png)

If none of those work, can you send me which version of windows you're using? You can find this out by running the program called `winver` from your search box.

**Comment by eatcodeplay** [comment]
Heya @Thomas101,

just checked what you asked for, my results:

* `Test Notification` does nothing (regardless of Notification Provider)
* Wavebox is listed in `Notifications & actions` and all required settings are enabled
* `Get Notifications from apps and other senders` is enabled
* Windows Version: Win 10 Pro Version 1703 Build 15063.608

Thx for looking into this. Are there any open Electron Bugs maybe? Haven't looked there yet.

**Comment by nmat** [comment]
Hello @Thomas101,

My results:
- Test Notification does nothing (no matter setting)
- Wavebox is listed
- checked settings and all should be fine but still no notifications

I have noticed that that I get notification sounds though from some services.

**Comment by eatcodeplay** [comment]
Have another finding as well. When downloading a file from any given service. The `Download Complete` Notification does appear. Not sure if that helps.

**Comment by Thomas101** [comment]
It looks we've broken the test notification button in one of the previous betas. Doh!

---

@eatcodeplay okay, the fact that you're getting the download complete notification indicates that the mechanism for showing them is working though. So it sounds like there's an issue with the sync. Which accounts do have added? If it's Gmail/Google Inbox can you try the steps [here](https://wavebox.io/kb/google-unread-counts). If it's Outlook/Office 365 can you try the steps [here](https://wavebox.io/kb/microsoft-unread-counts).

---

@nmat looking at the other issue you raised (#389) you probably need to enable the notifications for your added websites. As these have been added through the `Any Web Link` account type the notifications are only presented when the webpage tries to present them. Wavebox doesn't have any specific support for syncing unread messages/notifications on these until we get around to adding more integrations. In messenger, for example, it doesn't enable desktop notification automatically which is perhaps why you're not seeing any come up. To enable them...

* click the cog in the top left of the messenger window and then go to settings...
  ![screen shot 2017-09-20 at 10 00 41](https://user-images.githubusercontent.com/103586/30635527-9542ade0-9dea-11e7-8374-24dc43365f71.png)
* Tick the box next to `Desktop notifications enabled`
  ![screen shot 2017-09-20 at 09 56 58](https://user-images.githubusercontent.com/103586/30635546-a7785a3c-9dea-11e7-9358-877af4793377.png)

Once you've done this, you should start to see notifications coming up

**Comment by eatcodeplay** [comment]
Ah, i think you are on to something here. 

I exclusively use Custom Websites in Wavebox. Just tried calling the Notification Class from some of 'em and all of them actually work except for my very specific Exchange Outlook Web App Instance. 

It's the webmail for my workplace. My guess is that the Outlook Webapp actually overrides the Notification Class in that particular case. 

So i consider this issue solved for me. Here is hoping that your API will allow me to send Notifications again eventually ;)

**Comment by eatcodeplay** [comment]
Little addendum:

I also have a custom instance of Google Hangouts. I use it this way because i don't require the entire Google Gmail Stack added on Top. (**Idea:** maybe allow disabling Gmail in your Google Integration? :) )

In there the `new Notification('test')` call doesn't work either. May be the same issue as with the OWA instance? Again, not sure if Hangouts just overrides that Class there either.

**Comment by nmat** [comment]
That makes a lot of sense! Hmmmm can I offer a suggestion to have a warning when adding a custom service that "WARNING! In order to get notifications working you need to allow notifications in the service"

Or something like that. I guess it would help a lot of confusion.

**Comment by nmat** [comment]
Ok so.....experimental does not work.

Using default and slack etc works just fine. Have not tested the messenger thing now. Button of course does not work but that is fixed in the commit you added today I guess.

**Comment by Thomas101** [comment]
@nmat I'll see if I can get Susan here to write a blog about it and see what we can do in terms of screens!

**Comment by Thomas101** [comment]
Hi, 3.3.4 has just hit the beta channel with fixes for the test notification button. If you want to give it a try there's some more information on [how to get it here](https://wavebox.io/kb/beta-channel). Would be good to know if that works for everyone/if notifications have started working again etc

**Comment by eatcodeplay** [comment]
Test Notification Button works again as expected.

The issue remains with some custom websites. Most notably hangouts.google.com ( as described here: https://github.com/wavebox/waveboxapp/issues/327#issuecomment-330797927 ).

**Comment by Thomas101** [comment]
@eatcodeplay if you add hangouts.google.com as a service in 3.3.4 rather than a custom website you should get notifications and unread badges.

You will need to make sure hangouts is not set to sleep in settings. If you're adding a new Google account afresh sleep for hangouts will be disabled by default, if you're enabling it on an existing account you can find the toggle under ther Google Hangouts section in account settings

**Comment by eatcodeplay** [comment]
I think i don't quite understand, or we don't understand eachother ;) 
When you mean adding as a service, you mean adding the entire Gmail Stack right?
That is exactly what i'm trying to prevent. Since i don't check my Mails via Wavebox, i only would like to have hangouts and with your current implementation i would also be forced to add gmail as well :)

**Comment by Thomas101** [comment]
At the moment, we've only added Notification & badge support for hangouts when added under a gmail account. The "Any Web Link" accounts don't include any additional integrations for notifications or badges at the moment and as Hangouts doesn't produce Notifications out of the box they're not displayed.

We are working on adding more integrations along with the current Google, Microsoft, Trello and Slack offerings, hangouts can be one of these.

**Comment by Thomas101** [comment]
I'm going to close this off for now as the remaining comments now seem to be around different things to the original issue. If you're still having trouble, feel free to open up a new issue with a backlink to here and we'll take another look. Thanks

**Comment by eatcodeplay** [comment]
Just posting this in case anyone else is trying to get the existing `Notification` Class running in custom Weblinks. In order to be able to actually send the notification it is required to call this first:

```
Notification.requestPermission().then(() => { 
    /* you can send notifications now */ 
});`
```

This doesn't seem to be required for all Weblinks, but it is definitely the sureshot way to get you up and running ( sorry for double posting ).
