### ISSUE TITLE
Wavebox is just an empty frame

### ISSUE THREAD

**Issue by caldwed** [wavebox/waveboxapp#328]
* Which version of Wavebox are you using? 3.1.12 and/or 3.1.16
* Which Operating System are you using? Ubuntu 16.04

Something has happened to my installation and wavebox will no longer start... I just get an empty frame.

If I remove the ~/.local/share/wavebox directory it will start, but my accounts are obviously gone. Is there a clean way to re-import the account settings in this case?

**Comment by caldwed** [comment]
Apparently, if I delete the avatar_db.json file(s) it starts successfully. I have a lot of accounts with custom icons. Could the file be too big? It was large...

Is there a way to not encode the avatar, but instead point to an existing file or copy it to the local config directory?

**Comment by Thomas101** [comment]
There is a bug with 3.1.12 at the moment which means under certain circumstances with outlook/office365 accounts the avatar file can keep growing.

If you delete the file (as you already have) and re-try with 3.1.16 beta it shouldn't continue to grow - you will have to re-set your custom unfortunately. If you want to double check it's fixed with your install just restarting Wavebox shouldn't result in the file size growing.

We're hoping to push a release out to the stable and beta channels mid next week which will also include this fix.

**Comment by caldwed** [comment]
Thanks,

I've been trying 3.1.16, and have had it hang on me at least once a day.
Hopefully that issue will not also be in the next stable release.

I've backed down to 3.1.12, but I can go back to the beta if there is
specific debug info that you might find useful.

David Caldwell
david.j.caldwell@gmail.com

**Comment by Thomas101** [comment]
What happened when it froze up? Was it just a complete freeze or something else? The only thing I can think of, it the experimental window opener that's enabled by default in the beta channel.

Version 3.2.0 has just shipped which does include the avatar fix. Would be good to know how that works for you.

**Comment by caldwed** [comment]
I now have the 3.2 installed and it still freezes. The window is not responsive to input. The main window can be closed, but the tray icon functions do not work anymore.

There are many processes that are still running...

I'd be happy to gather logs for and experiment.

**Comment by Thomas101** [comment]
Hi, I'll see if I can reproduce anything my end. It would be great to know...

* What's the filesize of the `avatar_db.json` file? If you try quitting, removing this and starting again does it improve?
* Are you running 32-bit or 64-bit Ubuntu?
* Is the window constantly frozen or just sometimes?
* Which install method did you use (snap, deb, tar, repo)?

Thanks!

**Comment by mockturtl** [comment]
I have two Debian jessie 64-bit machines, Wavebox installed from repo v3.2.0-1.  Same accounts setup on both.

One always launches to an empty frame, the other works fine.

Will try removing `avatar_db.json` and report back.  

Let me know anything else I can try to help diagnose.

**Comment by mockturtl** [comment]
> Will try removing `avatar_db.json` [and `.backup`s]

Success! (and recovery of 2GB!)

**Comment by caldwed** [comment]
Following up:
- Removing the larger avatar_db.json file did fix the "empty frame" problem. I;m also using 3.2.2 from the beta channel.
- I still have an issue where wavebox will freeze after a while. I tend to start it and let it run all day. By the end of the day, it will typically be frozen. This means that the main window will not accept input, but it will minimize/restore. The icon in the tray (I'm using Ubuntu 16.04 running XFCE) will allow the main window to minimize/restore, but Quit does not work.

I have another Ubuntu machine and a Windows 10 machine that I can try to install on as well... let me see what else I can do.

(I think my original issue was fixed by the new release and/or deleting the avatar_db file. That issue can be closed. Maybe I should open a new one for the freeze...)

**Comment by Thomas101** [comment]
Thanks for the extra info. Great to know that removing the avatar db has fixed one issue.

Curious about the crash though. There's a couple of things that would be great to know...
* When it does freeze does Wavebox respond to any keyboard shortcuts? E.g pressing <kbd>Ctrl</kbd>+<kbd>&gt;</kbd> to move to the next account?
* If you installed from tar/deb, could you try running Wavebox from the terminal. There may be some error messages around the freeze. [Install locations](https://wavebox.io/kb/install-locations)
* Which accounts do you have and what types are they? (e.g. 1 outlook, 2 gmail, etc...)
* As you said, does it appear on the Windows machine

Thanks!
