### ISSUE TITLE
Webcam not available/accessible

### ISSUE THREAD

**Issue by Jan-Jan** [wavebox/waveboxapp#444]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.4.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Ubuntu 17.10

* To replicate

1. In Google Calendar open meeting
2. Click on hangout
3. This will open Wavebox with audio, but no access to webcam

**Comment by rodolfocam** [comment]
Can try with windows 10 64 pro?

**Comment by nmat** [comment]
@Jan-Jan does the same effect happen on both snap and .deb package?

Hangouts is still a bit of a fuzzy area AFAIK. Some support might not be there yet. But please test using the .deb package also to see if the camera works.

**Comment by Thomas101** [comment]
@Jan-Jan we've just tested with 17.04 and it seems to work here. If you try with your browser does that work? (Just wondering if it might be a driver configuration problem). If not I'll setup a 17.10 machine to see what happens

**Comment by luispabon** [comment]
Definitely doesn't work as a snap but works on .deb

**Comment by Thomas101** [comment]
@luispabon good point! @Jan-Jan what install method did you use?

**Comment by Jan-Jan** [comment]
It happened with the snap package.

I changed to Manjaro, and it works like a charm now. Thank you.

**Comment by luispabon** [comment]
@Thomas101 snap.

I don't think this issue should be closed though, it seems as though it is a real issue on the snap package.

**Comment by Thomas101** [comment]
@luispabon I agree. Must be a permission issue with the packages

**Comment by situmam** [comment]
I just tested it with version 3.5.1 on Ubuntu 17.10 and the camera works fine.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by maroc81** [comment]
Webcam wasn't working for me in hangouts with 3.7.0 until I manually connected the snap to camera. For others that have this problem you need to run the command:

`sudo snap connect wavebox:camera`

You can verify with the command

`snap interfaces`

where you should see the entry

`:camera                    wavebox`

Restart wavebox and webcam should now work.

**Comment by danielgblanco** [comment]
I recently installed Wavebox 3.14.5 (snap) on Ubuntu 18.04 and issue is still there. It was not until I connected the snap to the camera as @maroc81 mentions above that I got it working.

**Comment by Thomas101** [comment]
Connecting additional plugs/interfaces has to be done manually at the moment. The snap team are working on some kind of permission dialog to allow this on request. There's a KB on how to connect them [here](https://wavebox.io/kb/connect-snap-plugs). You might want to add `cups-control` if you want to print too
