### ISSUE TITLE
WaveBox does not remember zoom state on startup

### ISSUE THREAD

**Issue by amancevice** [wavebox/waveboxapp#447]
WaveBox `3.5.0` on macOS `10.13.1`

Applications on macOS can be set to full-screen mode where they occupy all screen real-estate. This feature is unique to macOS as far as I know and doesn't exist in Windows or Linux. macOS apps should remember their "zoom" state on exit and when re-opened they resume in the same state.

For an example of this behavior:

* Open Safari in macOS
* Enter full-screen mode by clicking the "zoom" button at the top-left of the window (close, minimize, zoom)
* Quit Safari
* Open Safari, see it open in full-screen mode

WaveBox used to do this but since ~3.4 or so, if I exit in full-screen mode the app will re-open expanded to fill the desktop, but not in the same full-screen mode.

**Comment by nmat** [comment]
This sounds a bit like: https://github.com/wavebox/waveboxapp/issues/393 ?

**Comment by amancevice** [comment]
I don't think so, @nmat. Maybe similar, but this issue is specific to macOS and I see #393 is specific to Windows.

I don't know if you've used macOS at all, but its full-screen mode is quite different than Windows. On macOS it's more like when you go full-screen in YouTube or Netflix.

**Comment by nmat** [comment]
@amancevice I just tested it on my macbook pro using 3.5.1 beta

On there the zoom is saved: Notice though that I am testing on a gmail account only on macOS High Sierra

I did also test it on my windows 10 pro machine and that saved the zoom also. (using google and mixed connections)

In both cases:
* they opened in fullscreen mode
* and zoom is saved

Have you set safari as the default browser or something in preferences?

**Comment by nmat** [comment]
sorry...I mean if there is a preference change at all that you have done? For example to use the "Use Zoom For DSF" or similar

**Comment by amancevice** [comment]
Thanks @nmat, I downloaded 3.5.1 from GitHub and tried it out: no luck.

The problem is a little hard to explain, so forgive me for being hyper-descriptive in my instructions.

Anyway, try this:

* In macOS, open WaveBox, go into full-screen/zoom mode (ctrl-⌘-F)
* Open mission control (gesture on track pad is three/four finger swipe up, if enabled)
* WaveBox *should* minimize to the top area of mission control along with "Desktop" and any other full-screen apps you have open
* If it does not minimize to the top of mission control then you're not in what I'm calling full-screen/zoom mode

Once you are *sure* you are in full-screen/zoom mode:

* Quit WaveBox
* Re-open WaveBox
* Open mission control
* See that WaveBox does **not** minimize to top of mission control, as it should, but is a normal window'd app

Let me know if this helps clear the issue up for you.

**Comment by nmat** [comment]
I just tested this. And according to my mission control it is on top next to Desktop.

Are you quiting wavebox in a specific way?

Also I verified it was fullscreen when I quit and started it.

**Comment by Thomas101** [comment]
As for the desired behaviour, I've given the steps that you described a try with Safari. Everything works the same, except Safari just re-opens as a window. The same way you described as being the wrong behaviour. I managed to get it to minimize up to the top area etc no bother!

The three things I can think of are....

1. Maybe I've got Mission Control configured differently. Can you send a screenshot of your settings from System Preferences?

2. It could be down to this commit.. https://github.com/wavebox/waveboxapp/commit/f988aff84ebb24bcf126c6a3d59d62266a81756a although reading through the changes I'm not 100% sure how, but this is the only thing that I know of that's changed around the fullscreen code

3.  I know you mentioned it worked with Safari, could you re-check? I'm wondering if the behaviour has changed in High Sierra slightly. Although I see the same behaviour between El Capitan and High Sierra.

**Comment by amancevice** [comment]
You're right, @Thomas101, I completely forgot that there is a default setting that needs to be changed (been so long since I un-ticked that box.

Go to `System Preferences => General` and uncheck the box that reads: `Close windows when quitting an app`

<img width="780" alt="screen shot 2017-11-02 at 7 45 19 am" src="https://user-images.githubusercontent.com/157711/32324440-d37aecde-bfa1-11e7-9432-7c4824c2163b.png">

**Comment by amancevice** [comment]
Hi, @Thomas101 & @nmat, just checking in on this

**Comment by Thomas101** [comment]
Okay, I see the same behaviour with that setting enabled. I'll take a look to see what's going on

**Comment by amancevice** [comment]
Thanks, & sorry for the run-around

**Comment by amancevice** [comment]
FYI, this behavior seems to be corrected in `3.6.0`

**Comment by Thomas101** [comment]
Awesome. Let me know if it comes back up!

**Comment by amancevice** [comment]
Oops... Looks like I spoke too soon. Seeing this behavior again after a reboot.

**Comment by Thomas101** [comment]
I've just given this another try on macOS 10.12.6 and also 10.13.1 and seem to see the correct behaviour. Are you still using 10.13.1 or have you updated macOS?

**Comment by amancevice** [comment]
Yes, I am on `10.13.2` now. The behavior appears to have improved somewhat but now when I start WaveBox the app appears briefly as its own desktop space but then slides away and I'm returned to the desktop space (even if I wasn't on the desktop before).

I'm attaching a gif to show you what I see:

<img src="https://i.imgur.com/Ir9zejl.gif"></img>

I did try this out on my iMac (which is also on `10.13.2`) and the behavior looks correct. However, after making the app full-screen and then going back to windowed the app seems to forget its windowed sizing and takes up the whole desktop area. That's probably not worth tracking in this particular issue, but just mentioning it.

**Comment by Thomas101** [comment]
Thanks for the gif. I'm wondering if this is a timing issue, which is why I'm having trouble reproducing it. If you click on the apple logo in the top left of the screen and go to `About this mac`, what's listed under Processor, Memory and Graphics? I'll see if we have a similar box here to try with. It might bring up this behaviour more reliably for me.

**Comment by amancevice** [comment]
<table>
<th>Component</th>
<th>Value</th>
<tr><td>Processor</td><td>2.7 GHz Intel Core i7</td></tr>
<tr><td>Memory</td><td>16 GB 2133 MHz LPDDR3</td></tr>
<tr><td>Graphics</td><td>Intel HD Graphics 530 1536 MB</td></tr>
</table>

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by amancevice** [comment]
Worked the first time, but on subsequent restarts the behavior remains. Sorry!

**Comment by Thomas101** [comment]
Hmmm, I'm seeing the correct behaviour. On the time that it failed, did you quit the app immediately or wait some time? The app waits a few seconds before saving the window position. I think a 5 - 10 second wait should be more than enough though

**Comment by amancevice** [comment]
On version `310.5beta` and the problem still persists -- but it's intermittent. I'd say it behaves correctly (opens in full-screen mode and doesn't immediately slide offscreen) every 1-in-7 times.

**Comment by Thomas101** [comment]
Thanks for the feedback. I'll have another try with it and see if I can find out why it's intermittent

**Comment by Thomas101** [comment]
3.12.0 has just gone out. The window restoration code works slightly differently now, as it was also causing some other issues #616. I've checked on our test box here and the fullscreen behaviour seems to be okay, but would be great if you could check if it's still intermittent for you!

**Comment by amancevice** [comment]
Looks good! Been closing/opening a couple times this morning and behavior seems consistent.

**Comment by amancevice** [comment]
This issue seems to have re-appeared in v10 :)

**Comment by Thomas101** [comment]
Yep you're right there! I'll take a look!
